#!/bin/bash
echo -e "\033[1;32m"
echo -e "                                                                    "
echo -e "  ################################################################  "
echo -e "  #                           一一一一                           #  "
echo -e "  #          天 下 程 式      |- ㄩ -|    都 會 有 BUG           #  "
echo -e "  #                  wv__   ㄒ|  免  |ㄒ   __vw                  #  "
echo -e "  #                       | | |  責  | | |                       #  "
echo -e "  #                        |  |  聲  |  |                        #  "
echo -e "  #                           |  明  |                           #  "
echo -e "  #                           一一一一                           #  "
echo -e "  ################################################################  "
echo -e "  #  檔名：Start.sh                                              #  "
echo -e "  #  全名：Startt Convolution Machine Of Bash Shell              #  "
echo -e "  #  The Program from : Lian0123                                 #  "
echo -e "  #  The Version : 0.0.1                                         #  "
echo -e "  ################################################################  "
echo -e "                                                                    "
echo -e "\033[0m"

echo -e "\033[1;32m"
printf "啟動程式. . . . . .\n"
node ~/code/SignalSystems/node_modules/.bin/electron ~/code/SignalSystems/
